name: Build Mod Menu
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Theos Manually
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Setup iOS SDK (Git Clone)
        run: |
          mkdir -p ~/theos/sdks
          git clone --depth=1 https://github.com/theos/sdks.git ~/theos-sdks
          mv ~/theos-sdks/iPhoneOS14.5.sdk ~/theos/sdks/
          rm -rf ~/theos-sdks

      - name: Build Tweak
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1 SYSROOT=~/theos/sdks/iPhoneOS14.5.sdk TARGET=iphone:clang:14.5:14.5 SDKTARGET=14.5
