name: Build Mod Menu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install ldid
        run: brew install ldid

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Build Tweak
        run: |
          export THEOS=~/theos
          export PATH=$THEOS/bin:$PATH
          make clean
          make package FINALPACKAGE=1

      - name: Upload Deb
        uses: actions/upload-artifact@v4
        with:
          name: DarkScript2-Package
          path: |
            *.deb
            packages/*.deb
            .theos/obj/*.deb
